version: "3"

services:
  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    env_file: .env
    command: npm start
    volumes:
      - /app/node_modules
      - ./packages/api:/app
    ports:
      - "8080:8080"

  ui:
    build:
      context: ./packages/ui
      dockerfile: Dockerfile.dev
    env_file: .env
    command: npm start
    volumes:
      - /app/node_modules
      - ./packages/ui:/app
    ports:
      - "3000:3000"
    stdin_open: true
